stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - configs/config.yaml
      - data/raw/WA_Fn-UseC_-HR-Employee-Attrition.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv